OP_JOIN = 'join'
OP_BYE = 'bye'
OP_BYE_R = 'bye_R'
OP_FIND = 'find'
OP_FIND_R = 'find_R'

OP_GETATTR = 'getattr'
OP_GETATTR_R = 'getattr_R'
OP_CREATE = 'create'
OP_LS = 'ls'
OP_LS_R = 'ls_R'

OP_READ = 'read'
OP_READ_R = 'read_R'
OP_WRITE = 'write'
OP_WRITE_R = 'write_R'
OP_TRUNC = 'truncate'
OP_TRUNC_R = 'truncate_R'
OP_GETXATTR = 'getxattr'
OP_GETXATTR_R = 'getxattr_R'

OP_LEAVE = 'leave'
OP_RENAME = 'rename'
OP_RENAME_R = 'rename_R'

OP_DELETE = 'delete'
OP_DELETE_R = 'delete_R'