OP_JOIN = 'join'
OP_BYE = 'bye'
OP_BYE_R = 'bye_R'
OP_FIND = 'find'
OP_FIND_R = 'find_R'

OP_GETATTR = 'getattr'
OP_GETATTR_R = 'getattr_R'
OP_CREATE = 'create'
OP_LS = 'ls'
OP_LS_R = 'ls_R'

OP_READ = 'read'
OP_READ_R = 'read_R'
OP_WRITE = 'write'
OP_WRITE_R = 'write_R'